### PR TITLE
Replace single changelog with one for each gem.

### PR DESCRIPTION
**Pull request by nhtruong**
With multiple gems coexisting in the same repo, the current framework for CHANGELOG.md is not suitable. We're going with a changelog for each gem and disable changelog verifier since it can't handle multiple change logs yet.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
But now we won't know what changed! What's the long term fix? I imagine we can combine the gems or have a CHANGELOG in each?

**Comment by nhtruong** [comment]
@dblock The commit messages will serve this purpose. Whenever you draft a new release, Github will pull the info of all commits since the last release for you to edit.

With 5 gems, each with its own version number, the long term solution is having a Changelog for each gem. It's the automated enforcement of changelog that's giving us trouble because it only works for 1 changelog file per repo. For now we're going to ask people to update the appropriate changelog when they offer a PR.

**Comment by harshavamsi** [comment]
@nhtruong I don't think we need the `dependabot_pr` file anymore. It only updated the changelog for each dependabot PR.

**Review by harshavamsi — DISMISSED** [review]

**Comment by dblock** [comment]
LGTM, needs a rebase

**Review by dblock — APPROVED** [review]
One of the problems with having all these gems in the same repo is tagging. Do we really want all of this to be lumped together if effectively we develop and release them separately?

**Review by harshavamsi — APPROVED** [review]

**Pull request merged**
