### PR TITLE
Added Sigv4 Debug Logging

### LINKED ISSUE #149: [FEATURE] Ability to print out Sigv4 Signature for debugging
### Is your feature request related to a problem?
Some users are seeing Authentication errors when using Sigv4 Client due to mismatching signatures. The ability to see what being signed and what the signature looks like will help us debug such issues.

### What solution would you like?
The option to print out sigv4 debug info

### Do you have any additional context?
Originated from https://github.com/opensearch-project/opensearch-ruby/issues/141

### PR DESCRIPTION
**Pull request by nhtruong**
### Issues Resolved
closes #149 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by harshavamsi — APPROVED** [review]

**Review by VachaShah — APPROVED** [review]
Can we also add the option to user guide?

**Comment by nhtruong** [comment]
@VachaShah good call. I'll add it in the follow up PR

**Comment by dblock** [comment]
I'm here late to this one ... This adds a whole new option just for sigv4 which feels like an overkill. Maybe we should have added a general logger to the client and set its level globally, then at DEBUG it would log the request/response?

**Comment by nhtruong** [comment]
I've thought of that. You can already do the logging for the transport layer with `log: true`. I was to also turn on the logging for Sigv4 when `log: true` is used. But then that forces Sigv4 logging on users who don't want or need it. Their log will be filled with Sigv4 logs all of a sudden after they upgrade.

**Comment by dblock** [comment]
I think my biggest issue is the addition of the `sigv4_debug` option. Loggers are usually configured directly, so I think users should be writing `Sigv4Client.logger.level = DEBUG`, not `Sigv4Client.new(sigv4_debug: true)`. 

I know the ship has sailed, but If you think that's better, you could deprecate this new option.

**Pull request merged**
